server:
  port: ${SERVER_PORT:8080}

logging.level.org.zalando.logbook: TRACE

logbook:
  include:
    - /v1/api/**
    - /actuator/**
  exclude:
    - /actuator/health
    - /api/admin/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 200
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
    write:
      chunk-size: 1000

management:
  info:
    git:
      mode: full

spring:
  profiles:
    active: local
  jackson:
    serialization:
      fail-on-empty-beans: false
  security:
    user:
      name: user
      passowrd: user
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-table: upm_change_log
    database-change-log-lock-table: upm_change_log_lock

logging:
  level:
    root: INFO

app:
  jwt:
    secret: ArbitrarySecretKey
    expiration-in-ms: 86400000 #1 day
    token.prefix: Bearer
    header.string: Authorization
---

spring:
  profiles: docker
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 200
      minimum-idle: 30
      idle-timeout: 3000
      pool-name: HikariCP
      jdbcUrl: ${JDBC_URL:jdbc:postgresql://database:5433/upm}
      username: user
      password: user
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

---

spring:
  profiles: local

  ###
  # HikariCP Properties
  ###
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 200
      minimum-idle: 30
      idle-timeout: 3000
      poolName: HikariCP
      jdbcUrl: ${JDBC_URL:jdbc:postgresql://localhost:5433/upm}
      username: user
      password: user
      driverClassName: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate

---
